sims_project/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

## [[ 2ByExample ]] 
## you can add password_reset 
## user register(new user) 
### Resetting password views  
## User registration   
## Extending User model  
## you need to implement user register functionality to extend user model 

sims_project/sims101/urls.py
from django.urls import path
from . import views

app_name = 'sims101'

urlpatterns = [ 
    path('', views.IndexListView.as_view(), name='index_list'), 
    path('data/<int:pk>/', views.IndexDetailView.as_view(), name='index_detail'), 
    path('data/create/', views.IndexCreateView.as_view(), name='index_create'), 
    path('data/<int:pk>/update', views.IndexUpdateView.as_view(), name='index_update'),
    path('data/<int:pk>/delete', views.IndexDeleteView.as_view(), name='index_delete'), 

]


# app_name = 'account'  domain  in urls.py 
# You need to use that namespace when reversing urls with reverse/reverse_lazy or {% url %}:
#  for example,  LOGIN_REDIRECT_URL = reverse_lazy('account:dashboard')

sims_project/sims_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView 
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls), 
    path('account/', include('account.urls')), 
    path('101/', include('sims101.urls')),    
    path('102/', include('sims102.urls')),   

]

## you can add login_required permission as follows.  
## path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
## In this project, it is not needed because  {% if user.is_authenticated %} is used in home.html template.

sims_project/sims101/models.py
from django.db import models
from django.urls import reverse

class Index101(models.Model):  
    department = "SNGRE DEPARTMENT ONE"
    index_name = "Index name is oneOneOne"
    description = "Here is the description of the index one....... "
    
    data_one = models.IntegerField()
    data_two = models.DecimalField(max_digits=5, decimal_places=2)
    calculated_value = models.CharField(max_length=32, blank=True, )  # to make it not visible in admin, use  editable=False

    class Meta:
        permissions = [
            ("index_manager", "Index Manager"), 
        ]

    def calculate(self):
        return self.data_one + self.data_two

    def save(self, *args, **kwargs):
        self.calculated_value =  self.calculate() 
        super(Index101, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.data_one) + "   " + str(self.data_two)

    def get_absolute_url(self):
        # or  return reverse('index_detail', args=[str(self.id)])
        return reverse('sims101:index_detail', kwargs={'pk': str(self.id)})
        # or you need to add success_url in CreateView and UpdateView

sims_project/sims101/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy 
from django.contrib.auth.mixins import PermissionRequiredMixin 
from .models import Index101

class IndexListView(PermissionRequiredMixin, ListView):
    permission_required = ('sims101.index_manager') 
    model = Index101                      ###  Or,   queryset = Post.objects.all()
    template_name = 'sims101/index_list.html'   ### default context name is 'object_list'. To change it, enter context_object_name = 'posts'
    ### paginate_by = 3       ## 3 objects per page 

class IndexDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ('sims101.index_manager') 
    model = Index101
    template_name = 'sims101/index_detail.html' ### default context name is 'object'. 

class IndexCreateView(PermissionRequiredMixin, CreateView):
    permission_required = ('sims101.index_manager') 
    model = Index101
    template_name = 'sims101/index_create.html'
    fields = ['data_one', 'data_two']
    login_url = 'login'
    ### CreateView, UpdateView에 success_url을 제공하지 않는 경우, 해당 model instance의 get_absolute_url 주소로 이동이 가능한지 체크한다 by Django ]]

class IndexUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = ('sims101.index_manager') 
    model = Index101
    template_name = 'sims101/index_update.html'
    fields = ['data_one', 'data_two']

class IndexDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = ('sims101.index_manager')    
    model = Index101
    template_name = 'sims101/index_delete.html'
    success_url = reverse_lazy('sims101:index_list')  
 

    # You can populate with some  initialization data, if needed: 
    # def get_initial(self, *args, **kwargs):
    #         initial = super(IndexCreateView, self).get_initial(**kwargs)
    #         initial['title'] = 'My Title'
    #         return initial
    # 

#     for CreateView and UpdateView, you can use form_valid for additional settings.
#     def form_valid(self, form):
#         form.instance.author = self.request.user 
#         return super().form_valid(form) 


    # # Initialize attributes shared by all view methods.
    # def setup(self, request, *args, **kwargs): 
    #     super().setup(request, *args, **kwargs)
    #     # get the Area objects using object ids passed by session 
    #     # this list will be sent to the template by the get_context_data() below
    #     if request.session._session:
    #         self.areas = [Area.objects.get(id=id) for id in request.session['affected_areas']] 

    # # Insert the area list  into the context dict.
    # def get_context_data(self, **kwargs):
    #     context = super(InformeDetailView, self).get_context_data(**kwargs)
    #     for example  self.kwargs['pk']   # pk is from the url 

    #     if request.session._session:
    #         context['areaset'] = self.areas
    #     return context

sims_project/sims101/templates/sims101/index_create.html
{% extends 'base.html' %}
{% block content %}
    <h4> New Index Data </h4>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

sims_project/sims101/templates/sims101/index_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1> Delete post </h1>
    <form action="" method="post">
        {% csrf_token %}
        <p> Are you sure you want to delete the data of {{ object.data_one }} {{ object.data_two }}? </p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

sims_project/sims101/templates/sims101/index_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="">
        <h2> {{ object.data_one }}</h2>
        <p> {{ object.data_two }} </p>
        <p> {{ object.calculated_value }} </p>
    </div>

    <p><a href="{% url 'sims101:index_update' object.pk %}"> +Edit Index Data </a></p>
    <p><a href="{% url 'sims101:index_delete' object.pk %}"> +Delete Index Data </a></p>
    <p><a href="{% url 'sims101:index_list'  %}"> +Go back to the list </a></p>

{% endblock content %}

sims_project/sims101/templates/sims101/index_list.html
{% extends 'base.html' %}
{% block content %}

    <a href="{% url 'sims101:index_create' %}">+ Add new index data</a> 

    {% for index in object_list %}
        <div >
            <a href="{% url 'sims101:index_detail' index.id %}">{{ index.data_one }}</a>
            <a href="{% url 'sims101:index_detail' index.id %}">{{ index.data_two }}</a> 
            <a href="{% url 'sims101:index_detail' index.id %}">{{ index.calculated_value }} </a>
        </div>
    {% endfor %}

    <p><a href="{% url 'home'  %}"> +Go back to Home </a></p>

{% endblock content %}

sims_project/sims101/templates/sims101/index_update.html
{% extends 'base.html' %}
{% block content %}
    <h3 class="my-3">Edit post</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-sm btn-info" value="Update" />
    </form>
{% endblock %}