sims_project/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

## [[ 2ByExample ]] 
## you can add password_reset 
## user register(new user) 
### Resetting password views  
## User registration   
## Extending User model  
## you need to implement user register functionality to extend user model 

sims_project/sims102/urls.py
from django.urls import path
from . import views

app_name = 'sims102'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index_list'), 
    path('data/<int:pk>/', views.IndexDetailView.as_view(), name='index_detail'), 
    path('data/create/', views.IndexCreateView.as_view(), name='index_create'), 
]

sims_project/sims_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView 
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls), 
    path('account/', include('account.urls')), 
    path('101/', include('sims101.urls')),    
    path('102/', include('sims102.urls')),   

]

## you can add login_required permission as follows.  
## path('', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
## In this project, it is not needed because  {% if user.is_authenticated %} is used in home.html template.

sims_project/sims102/models.py
from django.db import models
from django.urls import reverse

class Index102(models.Model):  
    department = "SNGRE DEPARTMENT Two 222"
    index_name = "Index 222 name is Percentage of Damage"
    description = "Here 222 is the description of the index ....... "

    data_one = models.IntegerField()
    data_two = models.DecimalField(max_digits=5, decimal_places=2)
    data_three = models.DecimalField(max_digits=5, decimal_places=2)
    calculated_value = models.CharField(max_length=32, blank=True, )  # to make it not visible in admin, use  editable=False

    def calculate(self):
        return self.data_one + self.data_two

    def save(self, *args, **kwargs):
        self.calculated_value =  self.calculate() 
        super(Index102, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.data_one) + "   " + str(self.data_two)

    def get_absolute_url(self):
        # or  return reverse('index_detail', args=[str(self.id)])
        return reverse('sims102:index_detail', kwargs={'pk': str(self.id)})

sims_project/sims102/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Index102

class IndexListView(ListView):
    model = Index102                       ###  Or,   queryset = Post.objects.all()
    template_name = 'sims102/index_list.html'   ### default context name is 'object_list'. To change it, enter context_object_name = 'posts'

class IndexDetailView(DetailView):
    model = Index102
    template_name = 'sims102/index_detail.html' ### default context name is 'object'. 

class IndexCreateView(CreateView):
    model = Index102
    template_name = 'sims102/index_create.html'
    fields = '__all__'
    ### CreateView, UpdateView에 success_url을 제공하지 않는 경우, 해당 model instance의 get_absolute_url 주소로 이동이 가능한지 체크한다 by Django ]]

 

    # You can populate with some  initialization data, if needed: 
    # def get_initial(self, *args, **kwargs):
    #         initial = super(IndexCreateView, self).get_initial(**kwargs)
    #         initial['title'] = 'My Title'
    #         return initial
    # 

sims_project/sims102/templates/sims102/index_create.html
{% extends 'base.html' %}
{% block content %}
    <h1> New Index Data </h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

sims_project/sims102/templates/sims102/index_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="">
        <h2> {{ object.data_one }}</h2>
        <p> {{ object.data_two }} </p>
        <p> {{ object.calculated_value }} </p>

    </div>
{% endblock content %}

sims_project/sims102/templates/sims102/index_list.html
{% extends 'base.html' %}
{% block content %}

    <a href="{% url 'sims102:index_create' %}">+ Add new index data</a> 

    {% for index in object_list %}
        <div >
            <a href="{% url 'sims102:index_detail' index.id %}">{{ index.data_one }}</a>
            <a href="{% url 'sims102:index_detail' index.id %}">{{ index.data_two }}</a> 
            <a href="{% url 'sims102:index_detail' index.id %}">{{ index.calculated_value }} </a>
        </div>
    {% endfor %}
{% endblock content %}